x-airflow-common: &airflow-common
  build:
    context: .
    dockerfile: Dockerfile.airflow
  env_file:
    - .env
  environment:
    - AIRFLOW__CORE__EXECUTOR=LocalExecutor
    - AIRFLOW__DATABASE__SQL_ALCHEMY_CONN=postgresql+psycopg2://${AIRFLOW_DB_USER:-airflow}:${AIRFLOW_DB_PASSWORD:-airflow_dev_password}@airflow-db:5432/${AIRFLOW_DB:-airflow}
    - AIRFLOW__CORE__FERNET_KEY=46BKJoQYlPPOexq0OhDZnIlNepKFf8Ep9aXi7aX4dYk=
    - AIRFLOW__CORE__LOAD_EXAMPLES=false
    - PYTHONPATH=/opt/airflow
  volumes:
    - ./airflow/dags:/opt/airflow/dags
    - ./pipeline:/opt/airflow/pipeline
    - ./data:/opt/airflow/data
    - ./reports:/opt/airflow/reports
    - ./sql:/opt/airflow/sql
  depends_on:
    airflow-db:
      condition: service_healthy

services:
  warehouse:
    image: postgres:16-alpine
    environment:
      - POSTGRES_USER=${WAREHOUSE_USER:-bi_user}
      - POSTGRES_PASSWORD=${WAREHOUSE_PASSWORD:-bi_dev_password}
      - POSTGRES_DB=${WAREHOUSE_DB:-warehouse}
    volumes:
      - warehouse_data:/var/lib/postgresql/data
      - ./sql/01_schema.sql:/docker-entrypoint-initdb.d/01_schema.sql
    ports:
      - "5433:5432" # mapped to 5433 to avoid host conflicts
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U bi_user -d warehouse"]
      interval: 5s
      retries: 5

  airflow-db:
    image: postgres:16-alpine
    environment:
      - POSTGRES_USER=${AIRFLOW_DB_USER:-airflow}
      - POSTGRES_PASSWORD=${AIRFLOW_DB_PASSWORD:-airflow_dev_password}
      - POSTGRES_DB=${AIRFLOW_DB:-airflow}
    volumes:
      - airflow_db_data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U airflow -d airflow"]
      interval: 5s
      retries: 5

  airflow-init:
    <<: *airflow-common
    command: version
    environment:
      - _AIRFLOW_DB_UPGRADE=true
      - _AIRFLOW_WWW_USER_CREATE=true
      - _AIRFLOW_WWW_USER_USERNAME=${_AIRFLOW_WWW_USER_USERNAME:-airflow}
      - _AIRFLOW_WWW_USER_PASSWORD=${_AIRFLOW_WWW_USER_PASSWORD:-airflow}
      - AIRFLOW__DATABASE__SQL_ALCHEMY_CONN=postgresql+psycopg2://${AIRFLOW_DB_USER:-airflow}:${AIRFLOW_DB_PASSWORD:-airflow_dev_password}@airflow-db:5432/${AIRFLOW_DB:-airflow}
    depends_on:
      airflow-db:
        condition: service_healthy

  airflow-webserver:
    <<: *airflow-common
    command: webserver
    ports:
      - "8080:8080"
    healthcheck:
      test: ["CMD", "curl", "--fail", "http://localhost:8080/health"]
      interval: 10s
      timeout: 10s
      retries: 5
    depends_on:
      airflow-init:
        condition: service_completed_successfully

  airflow-scheduler:
    <<: *airflow-common
    command: scheduler
    depends_on:
      airflow-init:
        condition: service_completed_successfully

  streamlit:
    build:
      context: .
      dockerfile: Dockerfile.streamlit
    ports:
      - "8501:8501"
    env_file:
      - .env
    volumes:
      - ./streamlit_app:/app/streamlit_app
      - ./pipeline:/app/pipeline
    depends_on:
      warehouse:
        condition: service_healthy

volumes:
  warehouse_data:
  airflow_db_data:
