"""PDF generation using WeasyPrint and actual BI data."""
import logging
from pathlib import Path

import pandas as pd
from weasyprint import HTML

from pipeline.db import make_engine

logger = logging.getLogger(__name__)


def generate_report_pdf(
    run_id: str,
    started_at_str: str,
    status: str,
    rows_extracted: int,
    rows_enriched: int,
    output_path: Path
) -> Path:
    """Generates a PDF report summarizing the run with real BI findings."""
    engine = make_engine()

    try:
        cat_df = pd.read_sql(
            f"SELECT category, COUNT(*) as count FROM mart.ticket_classifications WHERE run_id = '{run_id}' GROUP BY category ORDER BY count DESC LIMIT 3",
            engine
        )
        top_categories = "".join([f"<li>{row['category']}: {row['count']}</li>" for _, row in cat_df.iterrows()])
        if not top_categories:
            top_categories = "<li>No tickets classified in this run.</li>"

        anom_df = pd.read_sql(
            f"SELECT dimension, dimension_value, severity, deviation FROM mart.revenue_anomalies WHERE run_id = '{run_id}' ORDER BY deviation DESC LIMIT 3",
            engine
        )
        top_anomalies = "".join([f"<li>{row['severity'].upper()} anomaly in {row['dimension']} ({row['dimension_value']}): {row['deviation']:.1f} std dev</li>" for _, row in anom_df.iterrows()])
        if not top_anomalies:
            top_anomalies = "<li>No significant revenue anomalies detected.</li>"
    except Exception as e:
        logger.error(f"Failed to fetch BI insights for report: {e}")
        top_categories = "<li>Database not available.</li>"
        top_anomalies = "<li>Database not available.</li>"

    html_content = f"""
    <!DOCTYPE html>
    <html lang="en">
    <head>
        <meta charset="UTF-8">
        <title>BI Pipeline Run Report</title>
        <style>
            body {{ font-family: 'Helvetica Neue', Helvetica, Arial, sans-serif; padding: 20px; color: #333; }}
            h1 {{ color: #2c3e50; border-bottom: 2px solid #3498db; padding-bottom: 10px; }}
            h2 {{ color: #2980b9; margin-top: 30px; }}
            .summary {{ background: #f8f9fa; padding: 20px; border-radius: 8px; border-left: 4px solid #3498db; }}
            .metric {{ font-size: 1.1em; margin-bottom: 8px; }}
            .label {{ font-weight: 600; color: #555; display: inline-block; width: 150px; }}
            .status-success {{ color: #27ae60; font-weight: bold; background: #e8f8f5; padding: 3px 8px; border-radius: 3px; }}
            .status-failed {{ color: #c0392b; font-weight: bold; background: #fdedec; padding: 3px 8px; border-radius: 3px; }}
            .insights-box {{ background: #fff; border: 1px solid #ddd; padding: 20px; border-radius: 8px; margin-top: 20px; box-shadow: 0 2px 4px rgba(0,0,0,0.05); }}
            ul {{ line-height: 1.6; }}
            li {{ margin-bottom: 5px; }}
        </style>
    </head>
    <body>
        <h1>BI Pipeline Exec Summary / Résumé Exécutif</h1>

        <div class="summary">
            <div class="metric"><span class="label" style="width: 250px;">Run ID / ID d'exécution:</span> {run_id}</div>
            <div class="metric"><span class="label" style="width: 250px;">Started At / Démarré à:</span> {started_at_str}</div>
            <div class="metric"><span class="label" style="width: 250px;">Status / Statut:</span> <span class="status-{status.lower()}">{status}</span></div>
            <div class="metric"><span class="label" style="width: 250px;">Rows Extracted / Lignes Extraites:</span> {rows_extracted}</div>
            <div class="metric"><span class="label" style="width: 250px;">Rows Enriched / Lignes Enrichies:</span> {rows_enriched}</div>
        </div>

        <h2>Key Business Insights / Insights Clés</h2>
        <div class="insights-box">
            <h3>Top Ticket Categories / Principales Catégories</h3>
            <ul>
                {top_categories}
            </ul>

            <h3>Critical Revenue Anomalies / Anomalies de Revenus</h3>
            <ul>
                {top_anomalies}
            </ul>
        </div>

        <p style="margin-top: 40px; font-size: 0.9em; color: #7f8c8d; text-align: center;">
            This report was automatically generated by the AI-Enriched BI Pipeline.<br>
            Ce rapport a été généré automatiquement par le pipeline BI enrichi par l'IA.
        </p>
    </body>
    </html>
    """

    output_path.parent.mkdir(parents=True, exist_ok=True)
    logger.info(f"Generating PDF report at {output_path}")
    HTML(string=html_content).write_pdf(target=str(output_path))
    return output_path
