"""PDF generation using WeasyPrint."""
import logging
from pathlib import Path

from weasyprint import HTML, CSS

logger = logging.getLogger(__name__)


def generate_report_pdf(
    run_id: str,
    started_at_str: str,
    status: str,
    rows_extracted: int,
    rows_enriched: int,
    output_path: Path
) -> Path:
    """Generates a simple PDF report summarizing the run."""
    html_content = f"""
    <!DOCTYPE html>
    <html lang="en">
    <head>
        <meta charset="UTF-8">
        <title>BI Pipeline Run Report</title>
        <style>
            body {{ font-family: 'Helvetica Neue', Helvetica, Arial, sans-serif; padding: 20px; }}
            h1 {{ color: #2c3e50; }}
            .summary {{ background: #ecf0f1; padding: 15px; border-radius: 5px; }}
            .metric {{ font-size: 1.2em; margin-bottom: 10px; }}
            .label {{ font-weight: bold; }}
            .status-success {{ color: #27ae60; font-weight: bold; }}
            .status-failed {{ color: #e74c3c; font-weight: bold; }}
        </style>
    </head>
    <body>
        <h1>BI Pipeline Run Report</h1>
        <div class="summary">
            <div class="metric"><span class="label">Run ID:</span> {run_id}</div>
            <div class="metric"><span class="label">Started At:</span> {started_at_str}</div>
            <div class="metric"><span class="label">Status:</span> <span class="status-{status.lower()}">{status}</span></div>
            <div class="metric"><span class="label">Rows Extracted:</span> {rows_extracted}</div>
            <div class="metric"><span class="label">Rows Enriched:</span> {rows_enriched}</div>
        </div>
        <p>This report was automatically generated by the Automated BI Pipeline with AI Enrichment.</p>
    </body>
    </html>
    """

    output_path.parent.mkdir(parents=True, exist_ok=True)
    logger.info(f"Generating PDF report at {output_path}")
    HTML(string=html_content).write_pdf(target=str(output_path))
    return output_path
